[Unit]
Description=Flask App via Gunicorn
After=network.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/opt/flask_app

ExecStart=/usr/local/bin/gunicorn \
    --workers 3 \
    --bind 127.0.0.1:5000 \
    --access-logfile /var/log/app/gunicorn_access.log \
    --error-logfile /var/log/app/gunicorn_error.log \
    main:app

Restart=always
RestartSec=3

Environment="PYTHONUNBUFFERED=1"

StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
