- hosts: elasticsearch
  become: yes
  roles:
    - install-elastic
    - role: hostname
      vars:
        hostname: elasticsearch.lab.local
    - role: hardening
    - set-iptables
    - role: install-filebeat
