- hosts: wireshark
  become: yes
  roles:
    - install-xfce
    - install-wireshark
    - role: hostname
      vars:
        hostname: wireshark.lab.local
    - role: install-firefox
    - role: install-hack-tool
